### ISSUE TITLE
Similar project for D3D9 (d3d9on12.dll)

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/elf-auf-zwoelf#1]
Hi,
interesting project, don't know how doesn't get some publicity..
anyway just seeing also d3d9on12.dll (I'm on Win 20H1 insider build don't know if it's new or existed already) makes me wonder if possible similar project mapping D3D9 to D3D12?
thanks..

**Comment by doitsujin** [comment]
Is there any documentation for it?

**Comment by oscarbg** [comment]
seems not..
dependencies shows:
*GetPrivateDDITable
*OpenAdapter
*SetAppCompatData
and closest I found is:
https://lise.pnfsoftware.com/winpdb/758C5CACDA40B976DC1298B752623913F0D89EEEABF0D3B1FD3E8DF594862DD7-d3d9on12.html

**Comment by Rajalolxd** [comment]
There is someone who did that for Guild Wars 2

**Comment by Rajalolxd** [comment]
Wole

**Comment by oscarbg** [comment]
thanks @Rajalolxd I missed your response for two months! will try soon..
now we have the brother project: https://github.com/Joshua-Ashton/neun-auf-zwoelf
