### ISSUE TITLE
Should this work with wine?

### ISSUE THREAD

**Issue by RiantAnda** [doitsujin/elf-auf-zwoelf#4]
I've been trying this out due to the issue at https://github.com/doitsujin/dxvk/issues/3227.

With `d3d11.dll` in the game exe dir, MangoHud reports VKD3D, but the crash still happens.
![MW2_VKD3D](https://github.com/doitsujin/elf-auf-zwoelf/assets/43199243/e2e893b4-5224-4bbe-be83-56ea9e6d26a3)

From the log, there is something VKD3D wise happening (line 443+), but it seems like DXVK is still running the game(?):
[MW2.log](https://github.com/user-attachments/files/15862587/MW2.log)

Is there anything that could be done?

**Comment by doitsujin** [comment]
We implement the 11on12 interfaces by running DXVK on top of a vkd3d-proton device, so no, this isn't expected to do anything useful whatsoever on Linux.

**Comment by RiantAnda** [comment]
Thanks for the clarification!
